
# This file tells Netlify how to build and deploy your React application

[build]
  publish = "dist"  # This is the folder that gets deployed (Vite default)
  command = "npm run build"  # Simplified build command, assumes dependencies are already installed

# This is crucial for a React Router application
# It ensures all routes redirect to index.html so your client-side router can handle them
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variable configuration
[context.production.environment]
  VITE_APP_ENV = "production"
  VITE_PUBLIC_URL = "/"
  NODE_ENV = "production"
  CI = "true"  # Added to ensure builds are treated as CI

[context.deploy-preview.environment]
  VITE_APP_ENV = "preview"
  VITE_PUBLIC_URL = "/"

# Configure headers for security, caching, etc.
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Cache-Control = "public, max-age=31536000"

# Add specific headers for assets to improve caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Special headers for Lovable uploads
[[headers]]
  for = "/lovable-uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

# Add debugging info to deployments and specify Node version
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-optional"  # Make npm installs more reliable
